name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    
    - name: Build the Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
       image: http://172.16.238.245:8082/artifactory/remote-private/
       registry: docker.io
       dockerfile: ./docker/shipping/Dockerfile
       
    - name: Run command   
      run: |
        pwd
        cd docker/shipping
        docker build .
